plugins {
    id 'java'
}

group = 'WinRisk'
version = '1.0-SNAPSHOT'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.12'
}

// ensure tests use junit 4
test {
    useJUnit()
}
